version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: twitter
    volumes:
      - mongodb_data:/data/db

  node-dev:
    container_name: node-dev
    image: node:lts-alpine
    working_dir: /home/node/code
    volumes:
      - ./code:/home/node/code
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - mongodb
    tty: true
    command: sh -c "while sleep 1000; do :; done"

volumes:
  mongodb_data:
    driver: local
